### ISSUE TITLE
[BUG] - Cannot install module as described in README

### ISSUE THREAD

**Issue by kolbyd** [invernyx/smartcars-3-phpvms7-api#19]
### Describe the bug

I am following the steps outlined on the README (or at least, my interpretation of it). Although I have tried alternate installation methods (through the web interface, through artisan, etc.). None of these have worked.

The biggest issue appears to be that the laravel-modules package is not detecting it as a module.

### How do you reproduce this bug?

1. Navigate to the phpVMS `modules` directory
1. `curl -L -O https://github.com/invernyx/smartcars-3-phpvms7-api/releases/download/v0.5.0/SmartCARS3phpVMS7Api.zip`
1. `unzip SmartCARS3phpVMS7Api.zip`
1. `chown www-data:www-data SmartCARS3phpVMS7Api`. I do see that the module is waiting to be activated.
![image](https://github.com/user-attachments/assets/fd7793fe-2fa6-471f-9f53-3b7b209e088d)
1. After activating:
I cannot find the module in the modules page
![image](https://github.com/user-attachments/assets/70c3afeb-a9c8-4e6c-b167-fcd884e43288)
I can attempt to edit the module if I use the ID found in the modules table
![image](https://github.com/user-attachments/assets/2832ad58-297c-4d1b-a7b5-560e230761cc)

### Screenshots

![image](https://github.com/user-attachments/assets/9ce0fa42-a261-4a49-bdb1-38ba08712474)

`php artisan module:list` command

### API Version

0.5.0

### PHP Version

8.3.13

### Database & version

10.11.8-MariaDB-0ubuntu0.24.04.1

### Webserver version

nginx version: nginx/1.26.2

### Browser

Chrome 130.0.6723.117

**Comment by BossOfGames** [comment]
Did you try clearing your cache after enabling the module?

**Comment by kolbyd** [comment]
> Did you try clearing your cache after enabling the module?

Perhaps that what it was: I went back into the admin panel this morning and it said I had an update. There, I was able to run the migrations and everything is detecting properly now.

I appreciate the help, thank you!
