### ISSUE TITLE
[BUG] - Failed to fetch airports or bids after logging in - 401 HTTP Error

### ISSUE THREAD

**Issue by PilotFlying99** [invernyx/smartcars-3-phpvms7-api#21]
### Describe the bug

Whenever you login to smartCARS 3, it gives you errors fetching data.

Everything was set up correctly, especially the webs script URL is working fine. In addition, we followed this guide which brought no success: https://support.tfdidesign.com/support/solutions/articles/62000230353-failed-to-fetch-airports-or-bids-after-logging-in .

### How do you reproduce this bug?

Open smartCARS 3 and login to our VA.

### Expected behavior

Fetch latest data from phpVMS 7.

### Screenshots

![Screenshot 2024-12-07 004024](https://github.com/user-attachments/assets/d0601b76-a681-48b1-8c34-263f72a452fd)

### API Version

0.5.0

### PHP Version

8.2

### Database & version

Unknown

### Webserver version

TFDI Hosting

### Browser

Safari, Chrome, Firefox

### Additional context

This is the error from the error_log:

_"url":"https://website.com/api/smartcars/data/aircraft","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"name":"AxiosError","stack":"AxiosError: Request failed with status code 401\n_

**Comment by BossOfGames** [comment]
@PilotFlying99 Thanks for submitting this.

Can you please confirm the exact phpVMS version you're using please? A 401 code is a "unauthorized" code, which is highly peculiar.

Does your profile on phpVMS have an API key generated?

**Comment by PilotFlying99** [comment]
We're using the second-latest, phpVMS version 7.0.0-dev.g2a2602fa8b.

I just checked the MySQL Database. Indeed, the API keys are missing. Maybe they did override that information while the SQL Import. 

**So I have generated an API Key and the login is working now!**

However, is there an option to generate an API-Key for every user automatically, as we have more than 2.000 pilots?

**Comment by BossOfGames** [comment]
Good to hear.

For generating api keys for each individual member, I don't believe that exists unless the phpvms importer is used. It sounds like someone did a custom migration for your pilots.

I actually was in the same boat as you one time. If you're comfy with php and Laravel, you can write an artisan command to generate api keys for each user.

Just note that this goes beyond the scope of support for Invernyx, and I recommend you get help specifically from phpvms's support channels.
