### ISSUE TITLE
[BUG] - Smarcars3phpvms7api does not take into account fares for flight

### ISSUE THREAD

**Issue by CaptainGodual** [invernyx/smartcars-3-phpvms7-api#6]
### Describe the bug

I encountered an issue while using the SmartCarsPHPVMS7API library. The problem revolves around Calculating Ticket fares for a flight. This bug impacts the financial functionality of the PHPVMS7 usage with the Smartcars3PHPVMS7API.  In general ticket fares are not taken into account and calculated for finances for the Airline. 

### How do you reproduce this bug?

1. bid on Flight in PHPVMS7 or Smartcars3
2. Fly the complete Flight
3. File the Pirep

### Expected behavior

PIREP is filed and financial information is calculated by PHPVMS7 through the smartcars api. 

### API Version

0.4.4

### PHP Version

8.1

### Database & version

Most Recent MariaDB

### Webserver version

Recent Apache webserver

### Browser

Opera GX

**Comment by CaptainGodual** [comment]
This issue is in association with the following pull request https://github.com/invernyx/smartcars-3-phpvms7-api/pull/5

**Comment by GenericNerd** [comment]
As you said, this is already fixed through that pull request.
