### ISSUE TITLE
[BUG] - Smartcars 3 api  not detecting flight distance and flight duration mismatch

### ISSUE THREAD

**Issue by mohammedbkr** [invernyx/smartcars-3-phpvms7-api#7]
### Describe the bug

when you add a flight in the phpvms admin panel and you set the flight duration for one hour and you also set the distance, smartCARS 3 sets the flight duration as 1 hour (sets 60 minutes to 60 hours) and the distance is shown as NaN. Also, the smartCARS says that you are not in the correct airport even tho you are and in gate and not moving.

### How do you reproduce this bug?

when you add a flight in the phpvms admin panel and you set the flight duration for one hour and you also set the distance, smartCARS 3 sets the flight duration as 1 hour (sets 60 minutes to 60 hours) and the distance is shown as NaN. Also, the smartCARS says that you are not in the correct airport even tho you are and in gate and not moving.

### API Version

0.4.1

### PHP Version

8.2

### Database & version

5.7.44-Mysql

### Webserver version

Apache/2.4.59

### Browser

Opera GX

**Comment by GenericNerd** [comment]
@BossOfGames Is this something we can look into please?

**Comment by BossOfGames** [comment]
> ### Describe the bug
> when you add a flight in the phpvms admin panel and you set the flight duration for one hour and you also set the distance, smartCARS 3 sets the flight duration as 1 hour (sets 60 minutes to 60 hours) and the distance is shown as NaN. Also, the smartCARS says that you are not in the correct airport even tho you are and in gate and not moving.
> 
> ### How do you reproduce this bug?
> when you add a flight in the phpvms admin panel and you set the flight duration for one hour and you also set the distance, smartCARS 3 sets the flight duration as 1 hour (sets 60 minutes to 60 hours) and the distance is shown as NaN. Also, the smartCARS says that you are not in the correct airport even tho you are and in gate and not moving.
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### API Version
> 0.4.1
> 
> ### PHP Version
> 8.2
> 
> ### Database & version
> 5.7.44-Mysql
> 
> ### Webserver version
> Apache/2.4.59
> 
> ### Browser
> Opera GX
> 
> ### Additional context
> _No response_

smartCARS complaining that you're not at the correct starting airport is a unrelated issue to the other issue at hand, which is more a display bug caused by an incorrect API response.

For the second issue where you can't start a flight, can you please take a screenshot of what the `airports` table looks like for the airports affected?

A case where this would cause a problem is if the ARP (Airport Reference Point) is too far away from the aircraft when starting the flight.

**Comment by mohammedbkr** [comment]
![image_2024-04-28_120023418](https://github.com/invernyx/smartcars-3-phpvms7-api/assets/54552867/b7ab4237-ef41-4ed0-aaac-415faabe5561)
![image_2024-04-28_120034973](https://github.com/invernyx/smartcars-3-phpvms7-api/assets/54552867/f005f33d-50d0-4b9f-86ee-9841cb82ffc6)

here are the screenshots of the flights from phpvms and smartCARS 3

**Comment by mohammedbkr** [comment]
the Airport issue was from our side it's working perfectly. The only present issue is the issue I mentioned with the interface and the included screenshots

**Comment by BossOfGames** [comment]
That's what I figured.

v5 stores the time in hours and minutes separated by decimal, while v7 stores the value as total minutes as a integer, then uses a helper function to convert that to HH:MM for when it's called in the user interface though your website.

This is a similar case for the distance. Distance for v5 stores it as one unit and it's returned to the v5 api as such. v7 stores a unit in the database, then uses a helper function to convert the unit on the fly to the UI. What's being sent to smartCARS needs to be corrected.

For both issues, I have a fix I'm going to test in a little bit.

**Comment by BossOfGames** [comment]
@mohammedbkr 
![image](https://github.com/invernyx/smartcars-3-phpvms7-api/assets/2882332/1d1a2734-2c11-4a73-aed8-33e1d6014fc2)
Looks like I got it working.

Can you download this specific branch to confirm it on your end? You just need an updated FlightsController.php file.

https://github.com/invernyx/smartcars-3-phpvms7-api/tree/7-bug-smartcars-3-api-not-detecting-flight-distance-and-flight-duration-mismatch

**Comment by mohammedbkr** [comment]
I’ll check it and report back. Thank you!
